apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ui3r30c41-nodejs 
  janus-idp.io/tekton: ui3r30c41-nodejs
  backstage.io/kubernetes-id: ui3r30c41-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ui3r30c41-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml