apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ui3r30c41-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ui3r30c41-nodejs 
  name: ui3r30c41-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ui3r30c41-nodejs 
